social:
  github: bud1m
  email: budimir.filipovic1@gmail.com
  discord: bud1m

title: bud1m

description: >- # this means to ignore newlines until "baseurl:"
  Welcome to your new site, replace this description

# ===
# URL
# ===
#
# This is the base hostname & protocol for your site, as you see
# I use https://jekyllgems.github.io because this is a template
# and served live on my gh-pages site.
#
# Use localhost for local development
# http://localhost:4000


# =================
# EXCERPT_SEPARATOR
# =================
#
# This is used in your blog posts, you can see an example in any
# of the example blog posts included in this theme. It functions
# to trim your posts when displaying them so it doesnt show the
# entire post like on the front page. Feel free to change where
# the excerpt ends.

excerpt_separator: <!--more-->

# ==============
# BUILD SETTINGS
# ==============
#
# These are build settings needed for when you run "jekyll serve"
# commands. You can change these, but be careful because they can
# cause your site to break.
#
# COLLECTIONS
# ===========
#
# Collections are Jekylls way to handle things like tags, categories,
# authors. Any type of data you can iterate over. Here is how you add
# categories to your blog. Uncomment this to have it assign links for
# your categories
#
# collections:
#   categories: # This will create your category links
#     output: true
#     permalink: /:categories/:title/
#
# =======
# PLUGINS
# =======
#
# This is just one of the plugins you can use with jekyll
# you can find more useful plugins I have created at:
#
# https://github.com/jekyllgems/plugins

plugins:
  - jekyll-feed
